"""Synthesis-by-rule prosody, timing and coarticulation for ModernTalk.

Feeding a bare IPA phone stream to a Klatt synthesizer produces speech that is
phonetically complete but barely intelligible: it skips the duration, stress,
intonation and coarticulation machinery that the classic DECtalk *text* path
runs before it ever reaches the vocal-tract model. This module is that missing
machinery, generated by rule from the parsed IPA (:class:`~pyretrotts.ipa.
IpaClause`) -- its per-phone stress marks, word boundaries and clause terminator.

The rules are adapted (not copied) from the published synthesis-by-rule
literature, and each is cited at its source below:

* **Segment durations** -- Klatt (1979) "Synthesis by rule of segmental
  durations for English sentences" (in *Frontiers of Speech Communication
  Research*) and Klatt (1976) "Linguistic uses of segmental duration in English"
  (*JASA* 59(5)). Klatt's model gives every segment an inherent duration and a
  minimum ("incompressible") duration, and each rule scales the *stretchable*
  part by a percentage: ``dur = minimum + (inherent - minimum) * prcnt`` (Klatt
  1979 eq. 1), then adds pre-pausal lengthening. The rule *set* here mirrors the
  DECtalk ``us_phtiming`` stage (:mod:`pyretrotts.dectalk.timing`), which is
  itself a Klatt-1979 implementation, but uses this package's own manner-class
  tables rather than the proprietary US ROM.

* **Intonation / F0** -- the "hat pattern" of 't Hart, Collier & Cohen (1990)
  *A Perceptual Study of Intonation* and Cohen & 't Hart (1967) "On the anatomy
  of intonation" (*Lingua* 19): a declining baseline (declination) with a rise
  onto each accented syllable and a fall after it, plus a clause-final boundary
  tone selected by the terminator (statement fall, comma continuation rise,
  question final rise), after Pierrehumbert (1980) *The Phonology and Phonetics
  of English Intonation*.

* **Reduction** -- Lindblom (1963) "Spectrographic study of vowel reduction"
  (*JASA* 35(11)): unstressed vowels are both shortened and centralised toward
  schwa; the shorter the vowel, the more its formants undershoot their canonical
  target toward the neutral/locus value.

* **Coarticulation** -- locus theory of Delattre, Liberman & Cooper (1955)
  "Acoustic loci and transitional cues for consonants" (*JASA* 27(4)) and the
  target-undershoot model of Lindblom (1963): formants glide from a consonant's
  locus toward the vowel target at a roughly fixed *rate*, so short/unstressed
  segments never reach their target. The transition width therefore scales with
  segment duration; this replaces the flat three-point moving average.

* **Word boundaries** -- pre-boundary (phrase-final) lengthening, Klatt (1975)
  "Vowel lengthening is syntactically determined in connected discourse"
  (*Journal of Phonetics* 3) and Wightman et al. (1992) "Segmental durations in
  the vicinity of prosodic phrase boundaries" (*JASA* 91(3)): the segment before
  a word boundary is lengthened and a short inter-word transition is inserted --
  not a silent gap, which over-segments and costs intelligibility.

Durations are in ~6.44 ms Klatt frames (``pyretrotts.dectalk.consts``). All
frozen dataclasses; no synthesizer state lives here.
"""
from __future__ import annotations

import os
from dataclasses import dataclass

from ..ipa import IpaClause, Stress
from .features import FeatureBundle

__all__ = ["SegmentPlan", "plan_clause", "coarticulate", "reduce_vowel"]


def _on(name: str) -> bool:
    """Ablation gate (default on). Used only by the WER harness to measure each
    prosody component's contribution; production leaves every component on."""
    return os.environ.get(name, "1") != "0"


# --- intrinsic durations (Klatt 1979/1976), in ~6.44 ms frames --------------
# Each manner class carries an inherent duration (its citation-form length) and
# a minimum incompressible duration. Klatt 1979 assigns these per phone from
# measured English data; the manner-class values below are the medians of that
# table scaled to this synth's frame (vowel ~85 ms inherent / ~40 ms minimum,
# fricative ~70/50, stop closure ~55/40, nasal ~55/35, liquid ~45/25). Only the
# stretchable part (inherent - minimum) is scaled by the percentage rules.
_INHERENT = {
    "vowel": 13.0,
    "diphthong": 18.0,
    "stop": 5.0,        # closure only; the burst/aspiration are added by talk.py
    "fricative": 10.0,
    "affricate": 9.0,
    "nasal": 8.0,
    "approximant": 7.0,
    "lateral": 7.0,
    "trill": 8.0,
    "tap": 3.0,
}
_MINIMUM = {
    "vowel": 6.0,
    "diphthong": 9.0,
    "stop": 3.0,
    "fricative": 6.0,
    "affricate": 5.0,
    "nasal": 4.0,
    "approximant": 3.0,
    "lateral": 3.0,
    "trill": 4.0,
    "tap": 2.0,
}


@dataclass(frozen=True)
class SegmentPlan:
    """Rule-generated prosody for one IPA phone.

    ``dur_frames`` is the total segment duration (a diphthong's is split across
    its two glide halves by the caller). ``f0_hz`` is the F0 target at the
    segment's centre; the caller draws a piecewise-linear contour through the
    successive centres, giving declination and the accent hat pattern. ``reduce``
    (0..1) is how far an unstressed vowel is centralised toward schwa (the
    remaining formant undershoot is realised by :func:`coarticulate` from the
    segment's duration). ``pre_boundary`` marks a segment immediately before a
    word break.
    """

    dur_frames: int
    f0_hz: float
    reduce: float = 0.0
    pre_boundary: bool = False


def _manner_key(b: FeatureBundle) -> str:
    if b.is_vowel:
        return "vowel"
    return b.manner


def _duration(
    b: FeatureBundle,
    stress: Stress,
    *,
    clause_final: bool,
    pre_pausal: bool,
    pre_boundary: bool,
    in_cluster: bool,
    open_syllable: bool,
    n_phones: int,
) -> int:
    """Klatt-1979 duration for one segment, in frames.

    ``dur = minimum + (inherent - minimum) * prcnt`` with the percentage built
    from the multiplicative rules, then pre-pausal lengthening added. Each rule
    is tagged with its Klatt-1979 number.
    """
    key = _manner_key(b)
    inherent = _INHERENT.get(key, 7.0)
    minimum = _MINIMUM.get(key, 3.0)
    if b.long:                                   # phonemic length (IPA ː)
        inherent *= 1.6
    prcnt = 1.0

    is_vowel = b.is_vowel
    if is_vowel:
        # Rule 3 (stress): unstressed and secondary syllables are shortened; the
        # stretchable part of a primary-stressed vowel keeps its full length.
        if stress == Stress.NONE:
            prcnt *= 0.70
        elif stress == Stress.SECONDARY:
            prcnt *= 0.85
        else:
            prcnt *= 1.15                        # Rule 5: stressed lengthening
        # Klatt 1976: vowels are longer in open syllables (no tautosyllabic
        # coda) than in closed ones.
        if open_syllable:
            prcnt *= 1.10
    else:
        # Rule 6/13: a consonant inside a cluster or a polysyllable is shortened.
        if in_cluster:
            prcnt *= 0.85

    # Rule 2 / pre-pausal: clause-final rimes are lengthened; the effect is
    # strongest on the syllable nucleus (Klatt 1975).
    deldur = 0.0
    if clause_final and is_vowel:
        prcnt *= 1.35
    if pre_pausal:                               # segment abuts the pause
        deldur += 2.5
    # Pre-boundary (phrase-final) lengthening at a word edge (Wightman 1992):
    # smaller than clause-final, and it tapers off in long clauses.
    if pre_boundary and n_phones > 3:
        prcnt *= 1.12

    dur = minimum + (inherent - minimum) * prcnt + deldur
    return max(2, round(dur))


# --- intonation: declination + hat accents + boundary tone ------------------
# 't Hart/Cohen hat pattern and Pierrehumbert boundary tones, as multipliers on
# the speaker's base F0.
_DECLINATION = 0.18      # baseline falls ~18% across a clause ('t Hart 1990)
_ACCENT_PRIMARY = 1.12   # rise onto a primary-accented syllable (hat top)
_ACCENT_SECONDARY = 1.06
_FINAL_FALL = 0.90       # statement boundary: fall below the declined baseline
_CONT_RISE = 1.06        # comma / continuation rise (Pierrehumbert L-H%)
_QUEST_RISE = 1.20       # yes/no question final rise (H-H%)


def _f0_targets(
    clause: IpaClause, base_f0: float, *, is_last: bool
) -> list[float]:
    """One F0 target (Hz) per phone: declining baseline + hat accents + tone."""
    phones = clause.phones
    n = max(1, len(phones))
    terminator = clause.terminator
    out: list[float] = []
    # Index of the last syllabic phone, where the boundary tone is realised.
    vowel_idx = [i for i, p in enumerate(phones) if _looks_vowel(p.symbol)]
    last_vowel = vowel_idx[-1] if vowel_idx else n - 1
    if not _on("MP_F0"):
        return [base_f0] * n
    for i, phone in enumerate(phones):
        pos = i / n
        f0 = base_f0 * (1.0 - _DECLINATION * pos)   # declination
        if phone.stress == Stress.PRIMARY:          # hat rise
            f0 *= _ACCENT_PRIMARY
        elif phone.stress == Stress.SECONDARY:
            f0 *= _ACCENT_SECONDARY
        # Boundary tone on the final syllable, blended in over the last stretch.
        if i >= last_vowel:
            if terminator == "?":
                f0 *= _QUEST_RISE
            elif terminator == ",":
                f0 *= _CONT_RISE
            elif terminator in (".", "!", "") and is_last:
                f0 *= _FINAL_FALL
        out.append(f0)
    return out


_VOWEL_HINTS = frozenset("iɪɛeæaɑɒʌɔʊəɐɜɚɝɨouyʏøœɶʉɵɞɘɤɯ")


def _looks_vowel(symbol: str) -> bool:
    return bool(symbol) and symbol[0] in _VOWEL_HINTS


# --- reduction (Lindblom 1963) ----------------------------------------------
#: schwa formant targets (male voice), the centre reduction pulls toward.
_SCHWA = (550, 1300, 2550)


def reduce_vowel(b: FeatureBundle, amount: float) -> FeatureBundle:
    """Centralise a vowel's formants toward schwa by ``amount`` (0..1).

    Lindblom (1963): an unstressed, shortened vowel's articulation undershoots,
    so its formants move toward the neutral vocal-tract configuration (schwa).
    """
    if amount <= 0.0 or not b.is_vowel:
        return b
    from dataclasses import replace

    a = min(1.0, amount)
    f1 = round(b.f1 + (_SCHWA[0] - b.f1) * a)
    f2 = round(b.f2 + (_SCHWA[1] - b.f2) * a)
    f3 = round(b.f3 + (_SCHWA[2] - b.f3) * a)
    return replace(b, f1=f1, f2=f2, f3=f3)


def plan_clause(
    clause: IpaClause,
    bundles: list[FeatureBundle],
    base_f0: float,
    *,
    is_last: bool,
) -> list[SegmentPlan]:
    """Rule-generate a :class:`SegmentPlan` for every phone of ``clause``.

    ``bundles`` is the decomposed feature bundle per phone (the first segment of
    a multigraph is enough to classify manner). The returned list is parallel to
    ``clause.phones``.
    """
    phones = clause.phones
    n = len(phones)
    breaks = frozenset(clause.word_breaks)
    f0 = _f0_targets(clause, base_f0, is_last=is_last)
    plans: list[SegmentPlan] = []
    for i, phone in enumerate(phones):
        b = bundles[i]
        nxt = bundles[i + 1] if i + 1 < n else None
        prev = bundles[i - 1] if i > 0 else None
        clause_final = i == n - 1
        pre_pausal = clause_final
        # A word boundary falls immediately before phone ``i+1``: phone ``i`` is
        # word-final. Boundaries are stored as the index of the first phone of
        # the next word.
        pre_boundary = (i + 1) in breaks or clause_final
        in_cluster = (
            not b.is_vowel
            and ((prev is not None and not prev.is_vowel)
                 or (nxt is not None and not nxt.is_vowel))
        )
        # Open syllable: this vowel has no following tautosyllabic consonant
        # (next phone is a vowel or a word boundary follows).
        open_syllable = b.is_vowel and (
            nxt is None or nxt.is_vowel or (i + 1) in breaks
        )
        dur = _duration(
            b, phone.stress,
            clause_final=clause_final, pre_pausal=pre_pausal,
            pre_boundary=pre_boundary, in_cluster=in_cluster,
            open_syllable=open_syllable, n_phones=n,
        )
        if not _on("MP_DUR"):
            dur = round(_INHERENT.get(_manner_key(b), 7.0))
        reduce = 0.0
        if _on("MP_REDUCE") and b.is_vowel and phone.stress == Stress.NONE and not b.long:
            # Unstressed vowels centralise toward schwa (Lindblom 1963); the
            # duration-driven undershoot is added later by coarticulate(). Kept
            # gentle: strong centralisation erases the vowel identity an ASR
            # (and a listener) needs, so this nudges toward schwa rather than
            # collapsing onto it.
            reduce = 0.12
        plans.append(SegmentPlan(
            dur_frames=dur, f0_hz=f0[i], reduce=reduce,
            pre_boundary=pre_boundary,
        ))
    return plans


# --- coarticulation: duration-scaled locus transitions ----------------------

def coarticulate(
    frames: list[list[int]],
    smoothable: list[bool],
    seg_id: list[int],
    seg_dur: list[int],
    slots: tuple[int, ...],
) -> list[list[int]]:
    """Replace flat smoothing with duration-scaled locus transitions.

    ``seg_id[k]`` groups consecutive frames into segments; ``seg_dur[k]`` is that
    segment's frame count. For each formant ``slot`` a segment holds its own
    target across an interior plateau and *ramps* linearly to the neighbour's
    target across a transition window at each boundary. The window width scales
    with the neighbour's duration (locus theory, Delattre 1955): a long steady
    vowel gets a slow glide; a short/unstressed one is mostly transition, so its
    target is undershot (Lindblom 1963) exactly as measured.

    Only frames flagged ``smoothable`` participate; stop closures and bursts
    (``smoothable=False``) keep their crisp on/offsets, which carry the place
    cue. Non-smoothable and silent frames are never blended into.
    """
    n = len(frames)
    out = [list(f) for f in frames]
    if n == 0:
        return out
    from ..dectalk import consts as C

    if not _on("MP_COART"):
        # Fallback: the previous flat three-point moving average.
        for k in range(n):
            if not smoothable[k]:
                continue
            for slot in slots:
                acc, cnt = frames[k][slot], 1
                for j in (k - 1, k + 1):
                    if 0 <= j < n and smoothable[j] and frames[j][C.OUT_AV] > 0:
                        acc += frames[j][slot]
                        cnt += 1
                out[k][slot] = acc // cnt
        return out

    # Per-frame target = its own segment's formant value (the plateau target).
    for slot in slots:
        target = [frames[k][slot] for k in range(n)]
        for k in range(n):
            if not smoothable[k]:
                continue
            # Transition half-width: ~40 ms of glide (Delattre 1955), capped by
            # the shorter neighbouring segment so short vowels are dominated by
            # the transition and never reach their steady target.
            here = seg_id[k]
            # Position within the current segment run.
            val = target[k]
            acc = float(val)
            wsum = 1.0
            # Look outward up to 3 frames each way; weight falls with distance
            # and is gated by a duration-scaled window.
            for direction in (-1, 1):
                j = k + direction
                dist = 1
                while 0 <= j < n and dist <= 3:
                    if seg_id[j] == here:
                        j += direction
                        dist += 1
                        continue
                    if not smoothable[j] or frames[j][C.OUT_AV] <= 0:
                        break
                    # Window width from the *neighbour* segment's duration: a
                    # short neighbour pulls harder (wider relative influence).
                    ndur = max(1, seg_dur[j])
                    w = max(0.0, 1.0 - (dist - 0.5) / (3.5 - min(2.0, ndur / 4.0)))
                    if w <= 0.0:
                        break
                    acc += target[j] * w
                    wsum += w
                    j += direction
                    dist += 1
            out[k][slot] = round(acc / wsum)
    return out
