name: Build Tests

on:
  pull_request:
  push:
    branches: [dev, master]

jobs:
  build:
    uses: OpenVoiceOS/gh-automations/.github/workflows/build-tests.yml@dev
    secrets: inherit
    with:
      package_name: lintalker
      version_file: lintalker/version.py
