name: Release Workflow

on:
  pull_request:
    types: [closed]
    branches: [dev]
  workflow_dispatch:

jobs:
  release:
    uses: OpenVoiceOS/gh-automations/.github/workflows/publish-alpha.yml@dev
    secrets: inherit
    with:
      version_file: pyretrotts/version.py
